// Jenkinsfile (Declarative Pipeline)
pipeline {
   agent any
   
   
   stages {
      stage('Build') {
         steps {
            echo 'Building stage'
            sh 'mvn compile'
            sh 'mvn package'
            
         }
      }
      
      stage('Deploy') {
         when {
            expression {
               currentBuild.result == null || currentBuild.result == 'SUCCESS'
            }
         }
         
         // jenkins over ssh --
         steps {
            echo 'delivering app for deployment.'
            sh 'scp ./target/application-1.0.jar appuser@192.168.0.190:/home/appuser/apps/'
            sh 'ssh appuser@192.168.0.190 "nohup java -jar /home/appuser/apps/application-1.0.jar  & > /dev/null"'
            
            
            
         }
         
         
      }
      
      
      stage('End') {
         
         
         steps {
            echo 'done with deployment'
            sh 'echo "done"'
            sh 'exit'
            
            
            
         }
      }
      
   }
   
   }