// Jenkinsfile (Declarative Pipeline)
// Author:CodeFilmsPLC
pipeline {
   agent any
   
    parameters{
       string(name:'PID', defaultValue: '$2', description: 'java pid number')
       string(name:'PRINT',defaultValue: "'{print \$2}'", description:'print')
   } 
   
   stages {
      stage('Build') {
         steps {
            echo 'Building stage'     
            sh 'mvn clean package'            
         }
      }
      
      // there is docker
       stage('Containerize') {
         steps {
            echo 'Containerization stage'
            // get the dockerfile     
            sh 'docker build . -t codefilmsplc/jenkins-docker-app:alpha'
            //send the image to the hub
            sh 'docker image push codefilmsplc/jenkins-docker-app:alpha'
                        
         }
      }
      


stage('End') {
   steps {
   //   echo 'done with deployment'
    //  sh 'echo "done"'
      sh 'exit'
   }
}

}

}