// Jenkinsfile (Declarative Pipeline)
pipeline {
   agent any
   
   
   stages {
      stage('Build') {
         steps {
            echo 'Building stage'
            bat 'mvn compile'
            bat 'mvn package'
            
         }
      }
      
      stage('Deploy') {
         when {
            expression {
               currentBuild.result == null || currentBuild.result == 'SUCCESS'
            }
         }
         
         steps {
            echo 'Delivering app for deployment'
            sh 'scp ./target/application-1.0.jar appuser@appserver:/apps/'
            sh 'ssh appuser@appserver "nohup java -jar /apps/application-1.0.jar  &"'
            
            
         }
      }
      
   }
   
}